/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientsol;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author abhinav
 */
public class veiwclient extends javax.swing.JFrame {

    /**
     * Creates new form veiwclient
     */
    public veiwclient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        showmale = new javax.swing.JRadioButton();
        showfemale = new javax.swing.JRadioButton();
        showother = new javax.swing.JRadioButton();
        showcountry = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        showaddress = new javax.swing.JTextArea();
        showhindi = new javax.swing.JCheckBox();
        showenglish = new javax.swing.JCheckBox();
        showspanish = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        showchineese = new javax.swing.JCheckBox();
        showname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        searchclient = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        showdate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        showcid = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(showmale);
        showmale.setSelected(true);
        showmale.setText("male");

        buttonGroup1.add(showfemale);
        showfemale.setText("female");
        showfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showfemaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(showother);
        showother.setText("others");

        showcountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "india", "australia", "usa", "russia" }));

        showaddress.setColumns(20);
        showaddress.setRows(5);
        jScrollPane1.setViewportView(showaddress);

        showhindi.setText("hindi");
        showhindi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showhindiActionPerformed(evt);
            }
        });

        showenglish.setText("english");

        showspanish.setText("spanish");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("name:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("gender:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("DOB:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("country:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("address:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("language:");

        showchineese.setText("chineese");
        showchineese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showchineeseActionPerformed(evt);
            }
        });

        showname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shownameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dyuthi", 1, 24)); // NOI18N
        jLabel1.setText("veiw client");

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 51));

        jSeparator3.setBackground(new java.awt.Color(204, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(204, 0, 204));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "cid", "name", "gender ", "dob", "country", "address", "language"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("search client:");

        searchclient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchclientKeyReleased(evt);
            }
        });

        update.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("cid");

        showcid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showcid.setText("0");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(15, 15, 15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(showmale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(showfemale)
                                        .addGap(18, 18, 18)
                                        .addComponent(showother))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(showcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(showdate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(showname, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(showcid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(searchclient, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(showhindi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(showenglish))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(showspanish)
                                        .addGap(18, 18, 18)
                                        .addComponent(showchineese))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 57, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchclient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(showcid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showmale)
                    .addComponent(showfemale)
                    .addComponent(showother))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(showcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showhindi)
                    .addComponent(showenglish)
                    .addComponent(showspanish)
                    .addComponent(showchineese))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(update)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showfemaleActionPerformed
        // TODO add your handling updatede here:
    }//GEN-LAST:event_showfemaleActionPerformed

    private void showhindiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showhindiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showhindiActionPerformed

    private void shownameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shownameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shownameActionPerformed

    private void showchineeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showchineeseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showchineeseActionPerformed

    private void searchclientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchclientKeyReleased
       try{
        javax.swing.table.DefaultTableModel dtm=(javax.swing.table.DefaultTableModel)table.getModel();
        int rc=dtm.getRowCount();
        while(rc--!=0)
            dtm.removeRow(0);
        String t=searchclient.getText();
        dbconnect.read.setString(1,"%"+t+"%");
        ResultSet rs=dbconnect.read.executeQuery();
        while(rs.next())
        {
            java.util.Vector vec=new java.util.Vector();
            vec.add(rs.getInt("cid"));
            vec.add(rs.getString("name"));
            vec.add(rs.getString("gender"));
            vec.add(rs.getString("dob"));
            vec.add(rs.getString("country"));
            vec.add(rs.getString("address"));
            vec.add(rs.getString("language"));
            dtm.addRow(vec);
        }
       }catch(Exception e){JOptionPane.showMessageDialog(null, e);} 
    }//GEN-LAST:event_searchclientKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       try{
        int row=table.getSelectedRow();
        if(row!=-1){
        showcid.setText(table.getValueAt(row,0)+"");
        showname.setText((String)table.getValueAt(row,1));
        showaddress.setText((String)table.getValueAt(row,5));
   
        java.util.Date date=new java.text.SimpleDateFormat("dd-MMM-yyyy").parse((String)table.getValueAt(row, 3));
        showdate.setDate(date);
        showcountry.setSelectedItem((String)table.getValueAt(row, 4));
        if(table.getValueAt(row,2).equals("Male")){
            showmale.setSelected(true);
        }
        else if(table.getValueAt(row,2).equals("Female")){
            showfemale.setSelected(true);
        }
        else{
            showother.setSelected(true);
        }
        showhindi.setSelected(false);
        showenglish.setSelected(false);
        showspanish.setSelected(false);
        showchineese.setSelected(false);
        String language=(String)table.getValueAt(row, 6);
        if( !language.equals("") ){
                java.util.StringTokenizer st=
                        new java.util.StringTokenizer(language,",");
                while(st.hasMoreTokens()){
                    String s=st.nextToken();
                    if(s.equals("Hindi"))
                        showhindi.setSelected(true);
                    else if(s.equals("English"))
                        showenglish.setSelected(true);
                    else if(s.equals("Spanish"))
                        showspanish.setSelected(true);
                    else if(s.equals("Chineese"))
                        showchineese.setSelected(true);
                }
            }
        
        }
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
           int ans=JOptionPane.showConfirmDialog(null, "do you really wanna delete???","Deletion confirmation", JOptionPane.YES_NO_OPTION);
           if(ans==JOptionPane.YES_OPTION)
           {
               dbconnect.st.executeUpdate("delete from comp where cid='"+Integer.parseInt(showcid.getText())+"'");
               searchclientKeyReleased(null);
               JOptionPane.showMessageDialog(null, "successfully deleted!!!!");
           }
          
       }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       try{
           String gender;
                if(showmale.isSelected())
                    gender="Male";
                else if(showfemale.isSelected())
                    gender="Female";
                else
                    gender="Other";
                String s6="";
            if(showhindi.isSelected())
                s6+="Hindi,";
            if(showenglish.isSelected())
                s6+="English,";
            if(showspanish.isSelected())
                s6+="Spanish,";
            if(showchineese.isSelected())
                s6+="Chineese,";
             if( ! s6.equals("") ){
            s6=s6.substring(0, s6.length()-1);
        }
             java.text.DateFormat dateformat=new java.text.SimpleDateFormat("dd-MMM-yyyy");
             String date=dateformat.format(showdate.getDate());
        dbconnect.upd.setString(1, showname.getText());
        dbconnect.upd.setString(2, gender);
        dbconnect.upd.setString(3, date);
        dbconnect.upd.setString(4, (String)showcountry.getSelectedItem());
        dbconnect.upd.setString(5, showaddress.getText());
        dbconnect.upd.setString(6, s6);
        dbconnect.upd.setInt(7, Integer.parseInt(showcid.getText()));
        dbconnect.upd.executeUpdate();
         searchclientKeyReleased(null);
        JOptionPane.showMessageDialog(null, "Successfully updated");
       }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField searchclient;
    private javax.swing.JTextArea showaddress;
    private javax.swing.JCheckBox showchineese;
    private javax.swing.JLabel showcid;
    private javax.swing.JComboBox<String> showcountry;
    private com.toedter.calendar.JDateChooser showdate;
    private javax.swing.JCheckBox showenglish;
    private javax.swing.JRadioButton showfemale;
    private javax.swing.JCheckBox showhindi;
    private javax.swing.JRadioButton showmale;
    private javax.swing.JTextField showname;
    private javax.swing.JRadioButton showother;
    private javax.swing.JCheckBox showspanish;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
